### ISSUE TITLE
Align tool - point based glueing - renders models in same window - OS X

### ISSUE THREAD

**Issue by tonisvain** [cnr-isti-vclab/meshlab#269]
Hi.

i am new to meshlab but i encountered a problem with the aligning tool.
if i try to make the initial alignment with the point based glueing tool, it renders both of the model on top on each other. 

- all the mouse controls work as it should (one side of the screen controls one point cloud)
- the pictures are stretched horizontally
- the pictures are on top of each other

![screen shot 2018-01-20 at 00 43 38](https://user-images.githubusercontent.com/9446728/35175460-6c28149e-fd7c-11e7-96c9-a790ec4ca6f4.png)

**Comment by mcallieri** [comment]
Yes, sorry. It has been fixed in the code, we are working on a new release.

**Comment by stephanschulz** [comment]
I have the same issue with a fresh macOS download done yesterday.
I guess it says "build on dec 23 2016". so still the same issue ?

**Comment by mcallieri** [comment]
if you lok under "releases" you will find that for MacOS we do have various betas, where the bug has been fixed.

**Comment by stephanschulz** [comment]
oh. thanks so much.
I only saw the download link on the main website which still has the 2016 release linked.
but here is are the new ones: https://github.com/cnr-isti-vclab/meshlab/releases
