### ISSUE TITLE
glTF2 format support

### ISSUE THREAD

**Issue by vpenades** [cnr-isti-vclab/meshlab#441]
It could be nice if MeshLab could provide support for the glTF format.

There's already a number of libraries in C++ for it, like https://github.com/Microsoft/glTF-Toolkit

**Comment by goldragoon** [comment]
Is there any progress on this issue?
If not, I'd like to work with it.

**Comment by alemuntoni** [comment]
Hi @goldragoon, sorry but there is no progress on this :(
But PRs are welcome :)

**Comment by alemuntoni** [comment]
Hi everybody,
I've just added a gltf importer into meshlab!
Right now, only *.gltf files are supported (some material info, animations, skeleton etc. are ignored since they are not supported natively into meshlab). 
I plan to add support also for importing *.glb files and exporting gltf/glb in the future, therefore we can say that this feature request is done at 25% :). I still don't know when though.
You can try the importer by [downloading the last nightly build](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version). Looking forwards for your feedbacks!

**Comment by alemuntoni** [comment]
Another small update: now also *.glb files are supported (it was easier than I thought), therefore we can say that we are at 50%. :)
Hope to add the exporter in the near future!

**Comment by Tzanker** [comment]
@alemuntoni  thanks for the work so far! Do you have any update on exporting glb or gltf? I would find it really helpful!

**Comment by alemuntoni** [comment]
@Tzanker nope, sorry. It will require some time to implement it. Hope to have it by October/November..

**Comment by vpenades** [comment]
@alemuntoni Regarding writing glTFs, I would like to give you some advices:

It's not my use case, but I am aware that many MeshLab users do use it with models with millions of polygons. Now, glTF _does_ support very large meshes, but only _under certain conditions_.

- GLB files have a practical limit of 2Gb in size.
- glTF files have a practical limit of 2Gb on each binary blob, but a single glTF file can have multiple binary blobs.

So, for relatively (*) small meshes, I would use a generic glTF exporter...  but for very large meshes, I would use a domain specific exporter, where, each individual mesh would have a separated binary blob for positions, normals and UV coords. That way, the maximum number of vertices for a single mesh could be increased to  2Gb / 12 = 178 million vertices.

**Comment by alemuntoni** [comment]
Thanks for letting me know this, @vpenades!
I need to check if [tinygltf](https://github.com/syoyo/tinygltf) allows to control these scenarios, since it is the library we use for parse gltf in the importer, but should be fine.

**Comment by vanous** [comment]
This is very awesome, having the possibility to use meshlabserver and export glb would be really great!

**Comment by alemuntoni** [comment]
@vanous see #911

**Comment by vanous** [comment]
Yes, yes, i corrected myself fast, after noticing it :) . I just tested pymeshlab and it works well, great job!

**Comment by alemuntoni** [comment]
Oh ok, sorry @vanous! I still receive questions asking for meshlabserver, therefore it's kind of automatic for me to link that issue :D

**Comment by elenzil** [comment]
thrilled to see glb and gltf in meshlab!
seeing some issues, tho, and filed [this](https://github.com/cnr-isti-vclab/meshlab/issues/1064).

**Comment by mikeucfl** [comment]
> @Tzanker nope, sorry. It will require some time to implement it. Hope to have it by October/November..

Just curious if there has been any new updates for gLTF exporting, thanks!

**Comment by mark2142** [comment]
I am using pymeshlab.
I am trying to export a glb to obj.
I am getting this error.
failed to save ouput file Image processed/texture_1 cannot be saved. Your MeshLab version has not plugin to save file format.
What format is it trying to save?
Can it be fixed?

**Comment by gunmiosb** [comment]
I wanted to do the something similar as @mark2142 

- load a gltf/glb
- simplify it
- export as obj (because there is no gltf/glb exporter)

The problem seems to be embedded images in the gltf/glb file. If i use gltf/glb with external buffers/images the conversion works.

**Comment by malkasem** [comment]
> Hi everybody, I've just added a gltf importer into meshlab! Right now, only *.gltf files are supported (some material info, animations, skeleton etc. are ignored since they are not supported natively into meshlab). I plan to add support also for importing *.glb files and exporting gltf/glb in the future, therefore we can say that this feature request is done at 25% :). I still don't know when though. You can try the importer by [downloading the last nightly build](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version), and of course it will be included in the next meshlab version. Looking forward for your feedbacks!

Hi, I want to ask, if there is now possiblity to use MeshLab forimporting *.glb files and exporting gltf/glb ?

**Comment by ccdejene** [comment]
same issue:
* Export from glb to obj
 
texture_0 cannot be saved. Your MeshLab version has not plugin to save  file format.

any update on this ?

**Comment by fkxyyds** [comment]
> I am using pymeshlab. I am trying to export a glb to obj. I am getting this error. failed to save ouput file Image processed/texture_1 cannot be saved. Your MeshLab version has not plugin to save file format. What format is it trying to save? Can it be fixed?

I have encounterd same question .Had some progress?

**Comment by fkxyyds** [comment]
> same issue:
> 
> * Export from glb to obj
> 
> texture_0 cannot be saved. Your MeshLab version has not plugin to save file format.
> 
> any update on this ?

Did you solve it?I encountered the same problem.

**Comment by ccdejene** [comment]
@fkxyyds No sadly i wasn't able to find a workaround.
