### ISSUE TITLE
PR_a36436

### ISSUE THREAD

**Issue by Patrick-Chun** [cnr-isti-vclab/meshlab#604]
Hi all,

I am interested in developing and testing automated process for converting 3D LiDAR point cloud to surface mesh with a functionality that meshlabserver.exe provides.  
Here is a link that I found and it shows relevant information to implement.
[https://stackoverflow.com/questions/54143202/using-meshlab-function-with-python](url)
When I try to reproduce the steps shown in the link, I encountered this error. 
Failed to open file: PR_a36436 
Unfortunately, I got same error even if try with different point cloud set.
Please let me know if you have similar issues and resolved.

![error](https://user-images.githubusercontent.com/62224690/76715012-baced700-6700-11ea-9854-ebab12d4f7cf.gif)

**Comment by alemuntoni** [comment]
Could you please:
- tell which MeshLab version are you using;
- share the script;
- share the input obj file

thanks.

**Comment by Patrick-Chun** [comment]
Hi, Thank you for asking me the info and file.

MeshLab version is v2016.12
Here is the file. 
Please let me know if have any questions. 
[subsampled.zip](https://github.com/cnr-isti-vclab/meshlab/files/4345553/subsampled.zip)

**Comment by Patrick-Chun** [comment]
@alemuntoni 
Do you have any updates, comments?
What causes the issue "Failed to open file: PR_a36436"?

Thanks

**Comment by alemuntoni** [comment]
Where did you get the mlx script? It seems that there is a problem with the script.
I generated a [new one](https://github.com/cnr-isti-vclab/meshlab/files/4408219/my_script.mlx.zip), and that works on meshlabserver both 2016.12 and 2020.02.

**Comment by Patrick-Chun** [comment]
@alemuntoni 
Thank you for your help.
I created the script in meshlab 2016.12 based on the guideline shown in the link.  
[https://stackoverflow.com/questions/54143202/using-meshlab-function-with-python]
"First, load a mesh with Meshlab, run the filters you want to run, then go to filters >> show current filter script and save the script somewhere so you can call it with meshlabserver."

I tested the automated process with your script, but I met this error. 
Can you show your command line? 
This is my command line. 
meshlabserver -i input.obj -o output.ply -s script.mlx
![error1](https://user-images.githubusercontent.com/62224690/78087565-734a7b00-738f-11ea-81bb-39d4ee219371.gif)

**Comment by alemuntoni** [comment]
Could you please try the last MeshLab 2020.03? You can find [here](https://github.com/cnr-isti-vclab/meshlab/releases/download/Meshlab-2020.03/MeshLab2020.03-windows.exe). 
Before installing it, be sure to uninstall the old version of MeshLab.

**Comment by Patrick-Chun** [comment]
@alemuntoni 
It doesn't work in 2020.03 either. 
I've seen this error for the first time. Please refer to the pic. 
LOG: 2 ERROR - current folder is not writable. Screened Poisson Merging needs to save intermediate files in the current working folder. Project and meshes must be in a write-enabled folder. Please save your data in a suitable folder before applying.

![error1](https://user-images.githubusercontent.com/62224690/78205624-a150bd80-746a-11ea-88d8-6a6cf442329c.gif)

**Comment by alemuntoni** [comment]
Just running the command prompt as administrator should solve this last problem.
I was aware of this, and I'll solve it as soon as possible!

**Comment by Patrick-Chun** [comment]
I agree. But running as administrator still doesn't work. Are you fixing it?
![error admin](https://user-images.githubusercontent.com/62224690/78459574-f87fa980-7687-11ea-9f83-f7ae128835c8.gif)

![error admin](https://user-images.githubusercontent.com/62224690/78459597-1ea54980-7688-11ea-86f1-39f56819e503.gif)

**Comment by alemuntoni** [comment]
You should run meshlabserver.exe as administrator from a command prompt that has admin privileges......

Anyway, it has been fixed in [this](https://github.com/cnr-isti-vclab/meshlab/commit/c68a10bed42766a9fb8cb232b9a27c28f559572b) commit. 
You can download the installer [here](https://github.com/cnr-isti-vclab/meshlab/actions/runs/69255963).

**Comment by Patrick-Chun** [comment]
@alemuntoni 
I verified meshlabserver.exe works as admin. However, my output file is not created. 
This is the command to use: 
meshlabserver -i input.obj -o output.ply -s script.mlx
I can't see the output.ply file to C:\Program Files\VCG\MeshLab. 
Please let me know what was wrong with it. 
![miss output file](https://user-images.githubusercontent.com/62224690/78606279-0c174580-782b-11ea-8e71-2888c3eaad24.gif)

**Comment by alemuntoni** [comment]
Try to do as suggested in #621.
