### ISSUE TITLE
UI elements very small on 4k display

### ISSUE THREAD

**Issue by themightyoarfish** [cnr-isti-vclab/meshlab#662]
#### Check all platforms you experienced the issue (change to `[x]`)
- [ ] Windows
- [ ] Mac OS
- [X] Linux
- [ ] Every platform

#### What type of issue is?
- [X] bug or unexpected behavior
- [ ] crash
- [X] feature request
- [ ] other (specify...)

#### Describe your issue

Opening meshlab 1.3.2 on a 4k display with scaling factor 2 results in this:

![Screenshot from 2020-04-29 15-35-01@2x](https://user-images.githubusercontent.com/11613312/80602259-2d84df00-8a2f-11ea-9a90-3efabfbe3c71.png)

The UI is so small as to be almost unuseable.

**Comment by alemuntoni** [comment]
As you can see in the screenshot that you provided, 1.3.2 MeshLab version is 10 years old.
Please run a recent version and if the problem persists, open a new issue (it should not persist, I am using MeshLab from Ubuntu with a 4K monitor and it scales just fine).

**Comment by themightyoarfish** [comment]
Wow, did not realize this. Clearly the Ubuntu 18.04 apt package is outdated.

**Comment by alemuntoni** [comment]
Yep, it is! Ubuntu 2020.04 provides a recent meshlab version through apt (snap version is still an old one).

**Comment by themightyoarfish** [comment]
I do have this problem though that the font in this purple strip at the bottom is waay to small to read, even on the current master branch.

**Comment by alemuntoni** [comment]
Did you try the last [AppImage](https://github.com/cnr-isti-vclab/meshlab/releases/tag/Meshlab-2020.06)?

**Comment by themightyoarfish** [comment]
I tried it. Indeed the UI scale is larger across the board. In fact it's gargantuan. Probably more useable, but a bit over the top.
![Screenshot from 2020-06-06 10-34-57@2x](https://user-images.githubusercontent.com/11613312/83939995-76277900-a7e1-11ea-9e1a-15d694ab31fb.png)

**Comment by alemuntoni** [comment]
I think that there is something wrong on your system settings. Did you set some QT env variables for auto scale? 
Ubuntu 18.04 has a lot of issues on hidpi display, and a lot of them have been resolved on 20.04. I am 100% sure that this is not a problem related to MeshLab.

**Comment by themightyoarfish** [comment]
Whoops you're right, I had QT_SCALE_FACTOR set to 2. Without it, I still have the issue of the font inside the purple strip being unreadably small.
