### ISSUE TITLE
Excessive memory and poor performance with `bundle.out +  list.txt` and many images

### ISSUE THREAD

**Issue by eric-schleicher** [cnr-isti-vclab/meshlab#81]
In meshlab 2016.12, experiencing 2 seemingly related issues when working on `.out + .list` project with many (> 100) images..

1. The main window `on focus` event incurs a **very long** delay (while it seems to be enumerating the rasters) before becoming responsive again.

   This occurs *EVERYTIME* the focus (a) changes from a modal dialog back to the main window as well as (b) when switching/activating the meshlab window coming from another application.

   I looked through the windows performance monitor and watched for disk or other activity that would provide some clues as to what is going on.  I do not see any spikes of disk activity during this period, but the CPU core that meshlab is using hits 100%.

2. When opening projects like this (hundreds of camera/images) meshlab seems to load the complete rasters into memory at load time irrespective of whether raster mode is enabled?  It that required?  It's preventing me from opening projects with 4k images, and the workstation is reasonably equipped (32GB).

   Unfortunately when windows runs out of memory and I've had to forcibly stop meshlab before the system becomes unstable.

**Can someone confirm that this is what's happening, and whether there is a workaround or setting to change the behavior**.  It's a blocker until I figure out how to get the cameras into a project format that can be edited (trimmed down manually).

**Comment by mcallieri** [comment]
1- it is possible, we will test it. This problem, in the last version, was present for GEOMETRY layers, and it has been now corrected. It may well be that it is the same issue, and we just overlooked it because we normally use way more geometry layers than raster layers. In the previous version, a workaround was to hide the layer panel when not needed. It is annoying and not really a solution, but it worked.

2- yes, this one I can confirm: the rasters are always loaded completely from start. We are aware this is probably not the most efficient behavior, but there are NO PLANS for implementing an out-of-core strategy soon. 

3- related to this, we have a loading issue with projects with MANY geometry layers (more than 40-50), where loading becomes very slow. We are fixing it. This will be ok in the next release.

**Comment by zerg960** [comment]
I can confirm this is still an issue in 2020.07 - I'm unable to use Meshlab w/ a list.txt containing 3314 images, totaling 51.7 MB. (I've resized them all to 340x191 thinking it's a memory problem).

CPU load is around 13% but UI is frozen. After waiting for... a long time (at least 30+ minutes) the UI is responsive but doing anything with it results in another 20+ minute freeze - it's basically unusable.

**Comment by eric-schleicher** [comment]
note:  people reporting different level of CPU consumption on this issue is because we all have multi core machines.  watching the running process, it just consumes a whole core.

**Comment by zerg960** [comment]
yep. seems to be QT related; attaching a debugger has a lot of QT calls at the very top of the call stack.

and meshlabserver is able to process the files just fine.

**Comment by alemuntoni** [comment]
Hi everybody! 
Can someone share an example file that allows to reproduce the issue?
