### ISSUE TITLE
Poisson Surface Reconstruction filters failure

### ISSUE THREAD

**Issue by mardy** [cnr-isti-vclab/meshlab#93]
Hi there! I'm using Meshlab from the snap package, which I built from commit cc446b39dfc84d2354edce93043fc151e0e8e08e.
When I load a point set and activate the "Screened Poisson Surface Reconstruction" filter, the sub-window with the filter's option appears correctly, but immediately after pressing "Apply" I get a dialog saying that the filter failed (without any specific information about the error). On the log panel (in the bottom right of Meshlab's window) the text "Filter failed:" appears, but again nothing more is written.

I've also tried to rebuild meshlab from the 2016.12 release, but then the filter does not even appear in the menu.

Has anyone having more luck with this filter? If so, can you please tell me which git commit is known to work, so that I can build a Meshlab package having this filter enabled and working?

**Comment by cignoni** [comment]
There could be an issue with xml copying. Try to see issue #44 and pull request #55

**Comment by mardy** [comment]
So, with the changes suggested with the links you gave me, I built meshlab from the v2016-12 tag and there I've got the Poisson reconstruction working. However, if I checkout the current master, the Poisson reconstruction is not working. So it must have been broken during the last couple of months.

**Comment by cignoni** [comment]
Sorry for the wrong commit. I missed it (busy days)
 Corrected in ec6129c9fd9611c8276253f2e8f5566bbbe8d376
(We definitely need an automated build system)

BTW thanks again for the snap! 
checked merged your pull request and used  to upload the 'official' meshlab snap
https://uappexplorer.com/app/meshlab.cnr-isti-vclab

**Comment by mardy** [comment]
Hi, I've tested the very latest master branch (commit e1b31b727f351637544c11cc1eae63931120e08c) and the Poisson filter is still not working. It fails immediately.
Can you please check if it works for you? Do you have any idea of which commit might have broken it?
