### ISSUE TITLE
Transfer Vertex-Attributes To texture still crashes meshlab

### ISSUE THREAD

**Issue by jambus1986** [cnr-isti-vclab/meshlab#975]
Hi, 
Transfer Vertex-Attributes To texture still crashes meshlab
on the nightly from yesterday.

steps to reproduce:

- texture trivial-per triangle
   with default-Values,    texturesize 10000px

- Transfer Vertex-Attributes To texture still crashes meshlab
texture-path "test1"    without ".png"
Texture-size 10000x10000px

   allign texture =true
   Filltexture= true
   source:   simplecloud.ply
   dest:   simplemesh.ply

here is the link to sample-Data

https://we.tl/t-tmBWuTEtmG

greetings,

**Comment by alemuntoni** [comment]
Solved in the last commit.

**Comment by krwei** [comment]
Hi, 
sorry to reopen this issue but I'm having a similar problem. 
I tried to use the transfer: vertex attributes to texture function multiple times since yesterday to transfer color data from a point cloud to a texture for a corresponding mesh, but Meshlab crashed within seconds everytime I tried.
First I thought the complexity of the point cloud was the issue (77 mio points) but it still crashed with a cloud of around 3 mio points. Then I tried with a different mesh because I thought this specific mesh might be the issue. Still the same result, Meshlab just crashes.
I import the point clouds as a .ply file and the mesh as a .fbx file. The mesh has UVs.
And I made sure to install the latest version of Meshlab, so I tried with the older version I had and with the current version. Same result unfortunately.

Here is a link to the files I used on the second try:
https://syncandshare.lrz.de/getlink/fiBcJpUPqsC4V8gXYkcQLsc5/

Would be very glad if you could look into this. Many thanks!

**Comment by alemuntoni** [comment]
Fixed in the last commit. You can try the new build by downloading the [last nightly](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version).

**Comment by donny8** [comment]
Hi, sorry to reopen this issue, again.
But I'm still having the same problem.

I tested with one of the last 2024.12 nightly build [MeshLab_Windows_packages_x86_64](https://github.com/cnr-isti-vclab/meshlab/actions/runs/12374044111/artifacts/2332126177)

### Steps to follow
1. Open a mesh ( My sample is [here](https://drive.google.com/file/d/1oSNFTVH_QBH9VJMyEdmo9NrClr6eQmYX/view?usp=sharing) )
2. Execute the [Filters] - [Texture] - [Transfer: Vertex Attributes To texture (1 or 2 meshes)]
- Source Mesh: capsule.obj 
- Target Mesh: capsule.obj
- Color Data Source: **Texture Color**
3. Press "Apply" button
4. Meshlab crashes

Here is a short [video](https://drive.google.com/file/d/15qcOGnG7r8IjWHtXKSVT9Ex2MKad01y5/view?usp=sharing) demonstrating the procedure

I would really appreciate if you have a look at this issue, once again.
Thanks

**Comment by alemuntoni** [comment]
@donny8 the issue you described is different from the one described by OP. 
The crash should be fixed by the last commit.

**Comment by donny8** [comment]
I'd just checked the last commit fixed the crash.
Thanks a lot!
